### ISSUE TITLE
Need to have uniform case in project ID

### ISSUE THREAD

**Issue by radj** [wordpress-mobile/wpxmlrpc#13]
It took me a while to figure it the problem. I cloned the WordPress-iOS repository and my build kept failing because it could not find `#include <WPXMLRPC/...>` items. It turns out I cloned onto a case-sensitive volume. I simply recloned into a case-insensitive volume and could compile without a problem.

I think this is because the includes look for an all caps `WPXMLRPC` folder while the actual repo has a lower case `wpxmlrpc`.

**Comment by kim07** [comment]
:+1:
