### ISSUE TITLE
NSAllocateMemoryPages crash for @"\n" string

### ISSUE THREAD

**Issue by igrekde** [wordpress-mobile/wpxmlrpc#25]
Hi!
When you call the method `+ (NSData *)decodeString:(NSString *)string` with the parameter consisting only of control characters (\r, \n), there is a crash: `NSAllocateMemoryPages(4294967295)`.

The problem is in `void *NewBase64Decode` function, in the line `j += accumulateIndex - 1;`. For such kind of input data the accumulated Index is 0, so there is an integer overflow.

I'll make a PR with a quick fix of this bug:
```
        if (accumulateIndex > 0)
            j += accumulateIndex - 1;
```

**Comment by igrekde** [comment]
Hi again!
Can you release the new version with this fix? We still have to use my fork in our project.
Thanks!

**Comment by koke** [comment]
Updated to 0.8.1. Sorry I didn't reply sooner but I was on vacation.

**Comment by igrekde** [comment]
@koke thanks! :+1:
