### ISSUE TITLE
New higher level Wordpress Client

### ISSUE THREAD

**Issue by chrisballinger** [wordpress-mobile/wpxmlrpc#28]
We made `SCRWordpressClient` for a project that you may find useful:

* https://github.com/guardianproject/securereader_ios/blob/master/SecureReader/Views/SCRWordpressClient.h
* https://github.com/guardianproject/securereader_ios/blob/master/SecureReader/Views/SCRWordpressClient.m
* https://github.com/guardianproject/securereader_ios/blob/master/SecureReaderTests/SCRWordpressTests.m

It needs some slight modifications to make it 100% generic, but it's a good starting point.

Cheers!

**Comment by koke** [comment]
Nice, thanks for sharing!. We've been talking a WordPress API library/framework for a long time, but it just hasn't happened yet.

**Comment by chrisballinger** [comment]
Feel free to reappropriate this code, it's Apache 2.0
