### ISSUE TITLE
Large integer overflows

### ISSUE THREAD

**Issue by CognitiveDisson** [wordpress-mobile/wpxmlrpc#30]
Hi. I found a bug related to the method
```objective-c
- (NSNumber *)parseInteger:(NSString *)value
```
Parsing large integer overflows. I know that according to the specification xmlrpc int value must be 32-bit. But the response from the server is not possible to fix.
Example xml:
```xml
<?xml version='1.0'?>
<methodResponse>
  <params>
    <param>
      <value><int>9223372036854775808</int></value>
    </param>
  </params>
</methodResponse>
```
Parse result:
9223372036854775807 (64 bit process)

I'll make a PR with a fix of this issue. Is there a way to accept it or it’s better to fork?

**Comment by koke** [comment]
For reference, detailed explanation of the solution chosen here: https://github.com/wordpress-mobile/wpxmlrpc/pull/31#issuecomment-179372842
