### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by Praveeeenn** [wordpress-mobile/wpxmlrpc#39]
![screen shot 2016-08-15 at 12 02 05 am](https://cloud.githubusercontent.com/assets/11039436/17651058/9ba5ad1e-627b-11e6-8de1-4bb1a2aec594.png)

**Comment by stevebaranski** [comment]
@Praveeeenn thank you for reporting this issue. 

At the time of this writing, it can no longer be reproduced with the following inputs:

- v0.8.3 of `wpxmlrpc`
- Xcode 10.0 (10A254a)

Should you have additional questions or need additional assistance, please don't hesitate to open a new issue.
